// Energy: a lesson costs 10, an empty battery opens the energy sheet, an ad adds 10, Plus removes the limit.
import { webkit, devices } from 'playwright';
import fs from 'fs';
const fake = fs.readFileSync(new URL('./fake-supabase.js', import.meta.url), 'utf8');
const b = await webkit.launch();
const ctx = await b.newContext({ ...devices['iPhone 14'], viewport: { width: 390, height: 844 }, serviceWorkers: 'block' });
await ctx.route('https://cdn.jsdelivr.net/**', r => r.fulfill({ contentType: 'text/javascript', body: fake }));
await ctx.addInitScript(() => {
  if (localStorage.getItem('fake-session')) return;
  localStorage.setItem('fake-session', JSON.stringify({ user: { id: 'u1', email: 'n@x', user_metadata: { full_name: 'Nik' } } }));
  const now = Date.now();
  localStorage.setItem('english-cards:v1', JSON.stringify({ settings: { dir: 'en-ru', newPerDay: 10, onboarded: true, theme: 'light', themeSet: true }, progress: { 'en-ru': {}, 'ru-en': {} }, days: {},
    energy: { v: 14, at: now - 12 * 60000, t: now } }));
  sessionStorage.setItem('english-cards:letter', 'A');
});
const p = await ctx.newPage();
const errs = []; p.on('pageerror', e => errs.push(e.message));
const scr = () => p.evaluate(() => document.body.dataset.screen);
const chip = () => p.textContent('.energy-chip b');
await p.goto('http://localhost:8765/'); await p.waitForTimeout(900);
await p.tap('#splash', { position: { x: 30, y: 600 } }); await p.waitForTimeout(1400);
console.log('chip at start:', await chip());
await p.screenshot({ path: 'e-home.png' });
await p.tap('#app [data-study="*"]'); await p.waitForTimeout(700);
console.log('lesson 1 starts:', await scr());
await p.tap('.study-top [data-go="home"]'); await p.waitForTimeout(700);
console.log('chip after lesson:', await chip());
await p.tap('#app [data-study="*"]'); await p.waitForTimeout(800);
console.log('lesson 2 with 4 energy opens:', await scr(), '|', await p.textContent('.energy-title'), '|', await p.textContent('[data-energy-when]'));
await p.screenshot({ path: 'e-empty.png' });
await p.tap('[data-action="ad"]'); await p.waitForTimeout(700);
console.log('after ad:', await p.textContent('.energy-count'), '| start button:', !!(await p.$('.energy [data-study]')));
await p.screenshot({ path: 'e-after-ad.png' });
await p.tap('.energy [data-study]'); await p.waitForTimeout(700);
console.log('start from sheet:', await scr());
await p.tap('.study-top [data-go="home"]'); await p.waitForTimeout(700);
console.log('chip:', await chip());
await p.tap('.energy-chip'); await p.waitForTimeout(700);
await p.tap('[data-action="plus-on"]'); await p.waitForTimeout(700);
await p.screenshot({ path: 'e-plus.png' });
await p.tap('.sheet-bar [data-go]'); await p.waitForTimeout(700);
console.log('plus chip:', await chip(), '| cost on button:', !!(await p.$('.btn .cost')));
await p.tap('#app [data-study="*"]'); await p.waitForTimeout(700);
console.log('plus lesson:', await scr(), '| stored v:', await p.evaluate(() => JSON.parse(localStorage.getItem('english-cards:v1')).energy.v));
await p.tap('.study-top [data-go="home"]'); await p.waitForTimeout(600);
await p.tap('#tabs [data-go="settings"]'); await p.waitForTimeout(700);
await p.screenshot({ path: 'e-settings.png' });
console.log('errors:', errs);
await b.close();
