import { webkit, devices } from 'playwright';
import fs from 'fs';
const fake = fs.readFileSync(new URL('./fake-supabase.js', import.meta.url), 'utf8');
const b = await webkit.launch();
const ctx = await b.newContext({ ...devices['iPhone 14'], serviceWorkers: 'block' });
await ctx.route('https://cdn.jsdelivr.net/**', r => r.fulfill({ contentType: 'text/javascript', body: fake }));
await ctx.addInitScript(() => { if (!localStorage.getItem('english-cards:v1')) localStorage.setItem('english-cards:v1', JSON.stringify({ settings: { onboarded: true } })); });
const p = await ctx.newPage();
{ const tap = p.tap.bind(p); p.tap = async (sel, o) => { await p.locator(sel).first().evaluate(e => e.scrollIntoView({ block: 'center' })).catch(() => {}); await p.waitForTimeout(160); return tap(sel, o); }; }
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (/Content Security|Refused/i.test(m.text())) errs.push('CSP: ' + m.text()); });
p.on('dialog', d => { console.log('dialog:', d.message()); d.accept(); });
await p.goto('http://localhost:8765/');
await p.tap('#splash'); await p.waitForTimeout(400);
await p.tap('[data-action="signin"]'); await p.waitForTimeout(1200);
console.log('home has my-words prompt:', await p.isVisible('#app [data-edit=""]'));
await p.tap('#tabs [data-go="dict"]'); await p.waitForTimeout(500);
await p.screenshot({ path: 'mine-dict-empty.png' });
await p.tap('#app [data-go="word"]'); await p.waitForTimeout(600);
console.log('tabs hidden on editor:', await p.evaluate(() => document.getElementById('tabs').hidden));
await p.tap('[data-action="save-word"]'); await p.waitForTimeout(300);
console.log('empty-save toast:', await p.textContent('#toast'));
await p.fill('#f-word', 'sunshine');
await p.tap('[data-action="autofill"]');
await p.waitForFunction(() => !document.querySelector('[data-action="autofill"]').classList.contains('loading'), null, { timeout: 20000 });
const vals = await p.evaluate(() => ['translation','ipa','exEn','exRu'].map(k => document.getElementById('f-'+k).value));
console.log('autofill:', vals);
await p.screenshot({ path: 'mine-form.png' });
await p.tap('[data-action="save-word"]'); await p.waitForTimeout(700);
await p.screenshot({ path: 'mine-dict.png' });
// duplicate of a base word
await p.tap('#app [data-go="word"]'); await p.waitForTimeout(500);
await p.fill('#f-word', 'Hello'); await p.fill('#f-translation', 'привет');
await p.tap('[data-action="save-word"]'); await p.waitForTimeout(300); console.log('alert:', await p.textContent('.alert h2')); await p.screenshot({ path: 'hig-alert.png' }); await p.tap('[data-alert="1"]'); await p.waitForTimeout(700);
const st = await p.evaluate(() => JSON.parse(localStorage.getItem('english-cards:v1')).mine);
console.log('mine:', Object.values(st).map(w => w.word));
await p.tap('#tabs [data-go="home"]'); await p.waitForTimeout(500);
const firstTopic = await p.textContent('.list .list-title');
console.log('first topic on home:', firstTopic);
await p.tap('[data-study="Мои слова"]'); await p.waitForTimeout(600);
console.log('lesson first card:', await p.textContent('.flash .word'), '| total', await p.textContent('.study-top .num'));
await p.tap('[data-go="home"]'); await p.waitForTimeout(400);
// edit + delete
await p.tap('#tabs [data-go="dict"]'); await p.waitForTimeout(400);
await p.tap('.list-row[data-edit] .list-main'); await p.waitForTimeout(500);
console.log('editing:', await p.inputValue('#f-word'));
await p.tap('[data-action="delete-word"]'); await p.tap('[data-alert="1"]'); await p.waitForTimeout(600);
await p.waitForTimeout(2000);
const db = await p.evaluate(() => JSON.parse(localStorage.getItem('fake-db')));
console.log('cloud mine:', JSON.stringify(Object.values(db)[0].mine).slice(0, 300));
console.log('errors:', errs);
await b.close();
